name: meet_singles
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/pashune_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/pashune_logo.png"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  pinput: ^5.0.1
  flutter_svg: ^2.0.17
  lucide_icons: ^0.257.0
  video_player: ^2.9.5
  device_preview: ^1.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_card_swiper: ^7.0.2
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/svg/




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
